# Node docker image on which this would be run
image: node:latest

cache:
  paths:
    - node_modules/

services:
  - mongo

variables:
  NODE_ENV: 'test'

# Pipeline:
stages:
  - install
  - build
  - deploy
  - deploy-test

# Jobs:
install_dependencies:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

Build_and_Test:
  stage: build
  before_script:
    - npm run clean
  script:
    - npm run compile:all
    - npm test

coverage:
  stage: build
  script:
    - npm run test:report
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    paths:
      - coverage/

pages:
  stage: deploy
  dependencies:
    - coverage
  script:
    - mv coverage public
  artifacts:
    paths:
      - public
    expire_in: 30 days

deploy_production:
  image: ruby:latest
  only:
    - master
  stage: deploy
  before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
  script:
    - dpl --provider=heroku --app=$HEROKU_WIT_BANK_SERVER --api-key=$HEROKU_API_KEY
    - dpl --provider=heroku --app=$HEROKU_AIB_BANK_SERVER --api-key=$HEROKU_API_KEY
    - dpl --provider=heroku --app=$HEROKU_POST_OFFICE_SERVER --api-key=$HEROKU_API_KEY
    - echo "Deployed to WIT Bank server" 

deploy_production_dev:
  image: ruby:latest
  only:
    - master
    - develop
    - develop-test
    - develop-server
  stage: deploy-test
  before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
  script:
    - dpl --provider=heroku --app=$HEROKU_CREDIT_UNION_SERVER --api-key=$HEROKU_API_KEY
    - echo "Deployed to WIT Bank server" 

